# post http://localhost:3001/api/notes
# content-type: application/json

# {
#       "content": "Gerald Jay Sussman",
#       "important": true
# }

# get http://localhost:3001/notes

#get http://localhost:3001/api/notes/5a3b7c3c31d61cbd9f8a0343